<section class="mcare-inner-header">
  <div class="container">
    <div class="row">
      <h1> QUALITY COMMITTMENT</h1>
      <div class="crumbs"> <span><a href="<?php echo base_url();?>">Home</a></span> <span><a href="<?php echo base_url();?>">Pages</a></span> <span class="current-page">About Us Style 1</span> </div>
    </div>
  </div>
</section>
<!--About Us Content-->
<section class="mcare-aboutus-content">    <div class="container">      <div class="row">        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                    <h2 class="mcare-h2" style="margin:0 auto 30px;">Quality <span> Committment</span></h2>          <p class="text-content"><span class="caps-one">AFF</span> has always strived to deliver best quality products which shall support a healthy lifestyle in modern India. We have a robust logistics and supply chain mechanism that ensures premium quality food products reach across the globe. We make every effort to deliver quality products.</p>          <p class="text-content">Our farms and processing centres are located in close proximity to the major air and sea ports which ensures quick processing of fresh fruits and vegetables and thus substantially reducing the losses incurred due to rottening and decay of natural produce. AFF has developed strong backward linkages and an intelligent network for sourcing diverse agro commodities.</p>          <p class="text-content">From canned to aseptic and then IQF, we have embraced the latest technologies for food processing to meet the evolving demands of our global customer. Digital channels for food traceability onset at the farm level. Organisation wise ERP and CRM level up operational efficiencies across all geographies and offer real-time service to our customers. As we keep growing, we aspire to explore new geographies and devise new products for the global pallet</p>          <h2><span class="theme-color-text">Certifications</span> </h2>          <p class="text-content"><span class="caps-one">AFF</span> ensures adherence to the international quality requirements and standards while processing each of its products. We hold accreditations like ISO 22000:2005, FSSAI &amp; APEDA. We strive to ensure that no compromise on quality is incurred at any step of processing and the best product reaches the consumer.</p>          <p class="text-content">With our focus towards client’s satisfaction, we are climbing up ladders of enviable growth & success. All our products are offered after ensuring high quality standards are met and in are available in various pack sizes so as to fit into the diverse requirements of clientele globally. </p>          <p class="text-content"></p>          <p class="text-content"></p>        </div>              </div>    </div>  </section>
